# Generated by Django 6.0.1 on 2026-01-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('protein_type', models.CharField(choices=[('beef', 'Beef'), ('chicken', 'Chicken'), ('pork', 'Pork'), ('fish', 'Fish'), ('veggie', 'Veggie'), ('tofu', 'Tofu')], max_length=20)),
                ('ingredients', models.JSONField(default=list)),
            ],
        ),
    ]
