# Generated by Django 6.0.1 on 2026-01-26 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('plan_type', models.CharField(choices=[('generated', 'Generated'), ('manual', 'Manual Override'), ('skip', 'Skip Day')], default='generated', max_length=20)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.recipe')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
