# Generated by Django 6.0.1 on 2026-07-07 02:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mealplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Often (2x per rotation)'), (3, 'Favorite (3x per rotation)')], default=1, help_text='How many times this recipe appears per rotation cycle.'),
        ),
    ]
