# Generated by Django 6.0.1 on 2026-09-10 00:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_item_options_item_created_at_recipe_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('repair', 'Repair'), ('cleaning', 'Cleaning'), ('organization', 'Organization'), ('improvement', 'Home improvement'), ('yard', 'Yard & garden'), ('other', 'Other')], default='other', max_length=20)),
                ('urgency', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('scheduled_start', models.DateField(blank=True, null=True)),
                ('estimated_days', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_completed', '-urgency', models.OrderBy(models.F('scheduled_start'), nulls_last=True), '-created_at', '-pk'],
            },
        ),
    ]
