# Generated by Django 6.0.1 on 2026-09-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_householdproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdproject',
            name='project_type',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('repair', 'Repair'), ('cleaning', 'Cleaning'), ('organization', 'Organization'), ('app_tech_idea', 'App/Tech Idea'), ('ama', 'AMA'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
