# Generated by Django 6.0.8 on 2026-09-10 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_project_type_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('minute', models.BigIntegerField(default=0)),
                ('writes', models.PositiveIntegerField(default=0)),
                ('heavy', models.PositiveIntegerField(default=0)),
                ('ai_day', models.BigIntegerField(default=0)),
                ('ai_attempts', models.PositiveIntegerField(default=0)),
                ('ai_owner', models.CharField(blank=True, default='', max_length=32)),
                ('ai_until', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='householdproject',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
