# Generated by Django 6.0.8 on 2026-09-10 09:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_security_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('author', models.CharField(editable=False, max_length=64)),
                ('device_id', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.householdproject')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.CheckConstraint(condition=~models.Q(author=''), name='project_comment_household_author')],
            },
        ),
    ]
